pool:
  name: MyAgentPool

jobs:
- job: Build
  displayName: 'Build the project'
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet build --no-restore --configuration Release
    displayName: 'Build the project'

  - bash: echo hello world
