task: DotNetCoreCLI@2
displayName: 'Build the project'
inputs:
  command: 'build'
  arguments: '--no-restore --configuration Release'
  projects: '**/*.csproj'
pool: MyAgentPool
steps:
- bash: echo hello world